production:
  solr:
    hostname: localhost
    port: 8986
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8985
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8984
    log_level: WARNING
