production:
  solr:
    hostname: localhost
    port: 8986
    log_level: WARNING
    solr_home: <%= "#{Rails.root}/solr" %>
    path: /solr/production



development:
  solr:
    hostname: localhost
    port: 8985
    log_level: INFO
    max_memory: 5G
    solr_home: <%= "#{Rails.root}/solr" %>
    path: /solr/development


#
#	My default was around 1G and caused 
#		java.lang.OutOfMemoryError: Java heap space
#	after I added a lot of records.
#
#	java -XX:+PrintFlagsFinal -version
#
#	Set it to 2G here and seems to be happy
#
#	Now 2GB doesn't seem to be enough
#

test:
  solr:
    hostname: localhost
    port: 8984
    log_level: WARNING
    solr_home: <%= "#{Rails.root}/solr" %>
    path: /solr/test


